// Generated by CoffeeScript 1.11.1
module.exports = function(client, position_id, callback) {
  var params;
  params = {
    position_id: Number(position_id),
    market_close: true
  };
  return client.position.edit(params, callback);
};
