// Generated by CoffeeScript 2.2.3
module.exports = function(client, symbol, margin = 0.01, leverage = 1, callback) {
  var params;
  params = {
    symbol: market,
    margin: margin,
    direction: 'short',
    leverage: leverage,
    order_type: 'market'
  };
  return client.order.create(params, callback);
};
