'use strict';

// Generated by CoffeeScript 2.2.3
module.exports = function (client, symbol) {
  var margin = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : 0.01;
  var leverage = arguments.length > 3 && arguments[3] !== undefined ? arguments[3] : 1;
  var callback = arguments[4];

  var params;
  params = {
    symbol: market,
    margin: margin,
    direction: 'short',
    leverage: leverage,
    order_type: 'market'
  };
  return client.order.create(params, callback);
};