'use strict';

// Generated by CoffeeScript 2.3.0
var Big;

Big = require('big.js');

module.exports = function (price, amount, leverage) {
  return Number(amount / price * 100 * leverage).toFixed(2);
};