'use strict';

// Generated by CoffeeScript 2.2.3
var Big, details;

details = require('../../info/details.json');

Big = require('big.js');

module.exports = function (symbol, entry, current_price) {
  var decimals, point_size;
  decimals = details[symbol.toUpperCase()].decimals;
  point_size = 1 / Math.pow(10, decimals);
  return Number(new Big(current_price).minus(entry).div(point_size).toFixed(1));
};