// Generated by CoffeeScript 1.12.0
var call;

call = require('../call');

module.exports = function(config, position_id, callback) {
  var params;
  params = {
    position_id: position_id
  };
  return call(config, 'position/close', params, callback);
};
