'use strict';

// Generated by CoffeeScript 2.3.0
var call;

call = require('../call');

module.exports = function (config, params, callback) {
  if (params.take_profit === 0) {
    delete params.take_profit;
  }
  if (params.stop_loss === 0) {
    delete params.stop_loss;
  }
  return call(config, 'position/edit', params, callback);
};