'use strict';

// Generated by CoffeeScript 2.3.0
var call;

call = require('../call');

module.exports = function (config, params, callback) {
  return call(config, 'market/list', params, callback);
};