// Generated by CoffeeScript 1.11.1
var request;

request = require('request');

module.exports = function(config, method, params, callback) {
  var key, url, value;
  if (params && (callback == null)) {
    callback = params;
    params = null;
  }
  url = config.url + "/" + method + ".php?token=" + config.api_key;
  if ((config.referral_id != null) && !(params != null ? params.referral_id : void 0)) {
    url += "&referral_id=" + config.referral_id;
  }
  if ((params != null ? params.referral_id : void 0) != null) {
    url += "&referral_id=" + params.referral_id;
    delete params.referral_id;
  }
  if (config.pretty) {
    url += "&pretty=1";
  }
  if (params != null) {
    for (key in params) {
      value = params[key];
      console.log(key + "=" + value);
      url += "&" + key + "=" + value;
    }
  }
  return request({
    url: url,
    strictSSL: true
  }, function(error, response, body) {
    var e, parsed;
    if (error) {
      return typeof callback === "function" ? callback(error) : void 0;
    }
    try {
      parsed = JSON.parse(body);
    } catch (error1) {
      e = error1;
      console.log("error parsing body as json, dumping body");
      console.log(body);
      return typeof callback === "function" ? callback(e) : void 0;
    }
    if (body.error) {
      console.log(3);
      return typeof callback === "function" ? callback(body) : void 0;
    }
    if (body.warning) {
      console.log("Got Warning from API, dumping full response");
      console.log(body);
    }
    return typeof callback === "function" ? callback(null, parsed) : void 0;
  });
};
