// Generated by CoffeeScript 1.12.0
var _, default_config;

_ = require('lodash');

default_config = require('./config');

module.exports = function(api_key, referral_id) {
  var api, client, config, helper;
  if (!api_key) {
    console.error("Error: api_key is required to do 1broker API calls");
    return null;
  }
  config = _.defaults({
    api_key: api_key,
    referral_id: referral_id
  }, default_config);
  api = function(file) {
    return _.partial(require("./api/" + file), config);
  };
  client = {
    user: {
      details: api('user/details'),
      overview: api('user/overview'),
      bitcoin_deposit_address: api('user/bitcoin_deposit_address')
    },
    market: {
      details: api('market/details'),
      bars: api('market/bars'),
      list: api('market/list'),
      quotes: api('market/quotes')
    },
    order: {
      cancel: api('order/cancel'),
      create: api('order/create'),
      list_open: api('order/open')
    },
    position: {
      edit: api('position/edit'),
      history: api('position/history'),
      open: api('position/open'),
      close: api('position/close'),
      close_cancel: api('position/close_cancel')
    },
    info: module.exports.info,
    add: module.exports.add,
    get: module.exports.get
  };
  helper = function(file) {
    return _.partial(require("./helpers/" + file), client);
  };
  client.long = helper('long');
  client.short = helper('short');
  return client;
};

module.exports.info = {
  symbols: require('./info/symbols'),
  details: require('./info/details')
};

module.exports.add = {
  points: require('./helpers/add/points'),
  percentage: require('./helpers/add/percentage')
};

module.exports.get = {
  points: require('./helpers/get/points'),
  percentage: require('./helpers/get/percentage')
};
