// Generated by CoffeeScript 1.11.1
var _, default_config;

_ = require('lodash');

default_config = require('./config');

module.exports = function(api_key, referral_id) {
  var api, client, config, helper;
  if (!api_key) {
    console.error("Error: api_key is required to do 1broker API calls");
    return null;
  }
  config = _.defaults({
    api_key: api_key,
    referral_id: referral_id
  }, default_config);
  api = function(file) {
    return _.partial(require("./api/" + file), config);
  };
  client = {
    user: {
      details: api('user/details'),
      overview: api('user/overview'),
      bitcoin_deposit_address: api('user/bitcoin_deposit_address')
    },
    market: {
      detail: api('market/details'),
      get_bars: api('market/get_bars'),
      list: api('market/list'),
      quotes: api('market/quotes')
    },
    order: {
      cancel: api('order/cancel'),
      create: api('order/create'),
      list_open: api('order/open')
    },
    position: {
      edit: api('position/edit'),
      history: api('position/history'),
      open: api('position/open')
    },
    info: {
      symbols: require('./info/symbols')
    }
  };
  helper = function(file) {
    return _.partial(require("./helpers/" + file), client);
  };
  client.long = helper('long');
  client.short = helper('short');
  client.close = helper('close');
  return client;
};
