"use strict";

// Generated by CoffeeScript 2.2.3
module.exports = {
  url: 'https://www.1broker.com/api/v2',
  api_key: "",
  referral_id: 11468, // that's my default ID i would appreaciate this little help
  pretty: true,
  strictSSL: false
};