// Generated by CoffeeScript 1.12.0
var details;

details = require('../../info/details');

module.exports = function(symbol, value, points) {
  var decimals;
  decimals = details[symbol.toUpperCase()].decimals;
  points = points * (1 / Math.pow(10, decimals));
  return value + points;
};
