// Generated by CoffeeScript 1.11.1
var details;

details = require('../../info/details');

module.exports = function(symbol, price, points) {
  var decimals;
  points = Number(points);
  price = Number(price);
  decimals = details[symbol.toUpperCase()].decimals;
  points = points * (1 / Math.pow(10, decimals));
  return price + points;
};
